# Generated by Django 4.0.5 on 2022-06-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=5000)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='item_img')),
            ],
        ),
    ]
