# Generated by Django 4.0.5 on 2022-07-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopitems', '0003_alter_itemmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReveiw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rating_description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='rating',
        ),
    ]
