# Generated by Django 4.0.5 on 2022-07-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopitems', '0004_itemreveiw_remove_itemmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreveiw',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopitems.itemmodel'),
            preserve_default=False,
        ),
    ]
